services:
  # 1. База данных
  db:
    image: postgres:15
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: portfolio_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Бэкенд
  backend:
    build: ./backend
    container_name: portfolio_backend
    restart: always
    environment:
      - DATABASE_URL=postgres://portfolio_user:secret123@db:5432/portfolio_prod
    depends_on:
      - db

  # 3. Фронтенд (ОБНОВЛЕННЫЙ)
  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    restart: always
    ports:
      - "80:80"     # Для редиректа
      - "443:443"   # Для HTTPS
    volumes:
      # Магия: даем доступ к сертификатам внутри контейнера
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

  # 4. Админка БД
  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
